/**
 * Operator routes — token management, kick, invite script, hub health.
 *
 * Returns { villageRouter, hubRouter } since these endpoints span two URL prefixes:
 *   villageRouter → mount at /api/village  (kick, invite)
 *   hubRouter     → mount at /api/hub      (tokens CRUD, hub health)
 *
 * Dependencies injected by hub.js:
 *   tokenManager     — lib/token-manager.js
 *   processManager   — ProcessManager instance (for hub health running status)
 *   config           — { VILLAGE_SECRET, VILLAGE_HUB_URL, GAME_URL }
 *   limiter          — express-rate-limit instance
 */

import { Router } from 'express';
import { safeEqual, requireSecret } from '../lib/auth.js';

export function createOperatorRouters({ tokenManager, processManager, config, limiter }) {
  const { VILLAGE_SECRET, VILLAGE_HUB_URL, GAME_URL } = config;
  const authMiddleware = requireSecret(VILLAGE_SECRET);

  // ─── /api/village/* ────────────────────────────────────────────────────────

  const villageRouter = Router();

  // POST /kick/:botName — game server leave + token revoke
  // Token revocation means the bot's next poll returns 410 → clean exit.
  villageRouter.post('/kick/:botName', authMiddleware, async (req, res) => {
    const { botName } = req.params;
    const reason = req.body?.reason || 'Kicked by server';

    try {
      const headers = { 'Content-Type': 'application/json' };
      if (VILLAGE_SECRET) headers['Authorization'] = `Bearer ${VILLAGE_SECRET}`;
      await fetch(`${GAME_URL}/api/leave`, {
        method: 'POST',
        headers,
        body: JSON.stringify({ botName }),
        signal: AbortSignal.timeout(10_000),
      });
    } catch { /* best-effort */ }

    try { await tokenManager.revoke(botName); } catch { /* best-effort */ }

    console.log(`[hub] kicked ${botName}: ${reason}`);
    res.json({ ok: true, botName, reason });
  });

  // POST /invite/:token — one-time bash setup script for remote bots
  villageRouter.post('/invite/:token', limiter, async (req, res) => {
    const { token } = req.params;
    if (!token || !token.startsWith('vtk_')) {
      return res.status(400).type('text/plain').send('Invalid invite token.\n');
    }

    const tokens = await tokenManager.read();
    const entry = tokens[token];
    if (!entry || !entry.botName) return res.status(404).type('text/plain').send('Invite not found.\n');
    if (entry.claimedAt)          return res.status(410).type('text/plain').send('This invite has already been used.\n');

    try {
      await tokenManager.update((data) => {
        if (data[token]) data[token].claimedAt = new Date().toISOString();
      });
    } catch (err) {
      console.error(`[hub] Failed to mark invite as claimed: ${err.message}`);
    }

    const script = `#!/usr/bin/env bash
set -euo pipefail

# --- Village Plugin Setup ---
# Generated by OpenClaw Village Hub. Run: curl <url> | bash

VILLAGE_HUB="${VILLAGE_HUB_URL}"
VILLAGE_TOKEN="${token}"

echo "Installing village plugin..."
openclaw plugins install ggbot-village@latest

# --- Add env vars to gateway.env ---
OPENCLAW_DIR="\${1:-}"
if [ -z "\$OPENCLAW_DIR" ]; then
  if [ -d "\$HOME/.openclaw" ] && [ -f "\$HOME/.openclaw/openclaw.json" ]; then
    OPENCLAW_DIR="\$HOME/.openclaw"
  elif [ -d ".openclaw" ] && [ -f ".openclaw/openclaw.json" ]; then
    OPENCLAW_DIR=".openclaw"
  else
    echo "Error: Cannot find OpenClaw directory."
    echo ""
    echo "Usage: curl <url> | bash -s /path/to/.openclaw"
    echo "  or run from the directory containing .openclaw/"
    exit 1
  fi
fi

ENV_FILE=""
for candidate in "\$OPENCLAW_DIR/../gateway.env" "\$OPENCLAW_DIR/gateway.env"; do
  if [ -f "\$candidate" ]; then
    ENV_FILE="\$candidate"
    break
  fi
done

if [ -n "\$ENV_FILE" ]; then
  sed -i '/^VILLAGE_HUB=/d; /^VILLAGE_TOKEN=/d' "\$ENV_FILE"
  echo "VILLAGE_HUB=\$VILLAGE_HUB" >> "\$ENV_FILE"
  echo "VILLAGE_TOKEN=\$VILLAGE_TOKEN" >> "\$ENV_FILE"
  OWNER=\$(stat -c '%u:%g' "\$ENV_FILE" 2>/dev/null || echo "")
  if [ -n "\$OWNER" ] && [ "\$OWNER" != "\$(id -u):\$(id -g)" ]; then
    chown "\$OWNER" "\$ENV_FILE" 2>/dev/null || true
  fi
  echo "Added env vars to gateway.env"
else
  echo ""
  echo "No gateway.env found. Add these to your environment:"
  echo "  VILLAGE_HUB=\$VILLAGE_HUB"
  echo "  VILLAGE_TOKEN=\$VILLAGE_TOKEN"
fi

echo ""
echo "Done! Restart your bot to join the village."
`;

    res.type('text/plain').send(script);
  });

  // ─── /api/hub/* ────────────────────────────────────────────────────────────

  const hubRouter = Router();

  // POST /tokens — issue a new vtk_ token + invite URL
  hubRouter.post('/tokens', authMiddleware, async (req, res) => {
    const { botName, displayName } = req.body || {};
    if (!botName) return res.status(400).json({ error: 'Missing botName' });

    try {
      const token     = await tokenManager.generate(botName, displayName);
      const inviteUrl = `${VILLAGE_HUB_URL}/api/village/invite/${token}`;
      console.log(`[hub] issued token for ${botName}: ${token}`);
      res.json({ ok: true, token, inviteUrl, botName });
    } catch (err) {
      console.error(`[hub] token generation failed: ${err.message}`);
      res.status(500).json({ error: 'Failed to generate token' });
    }
  });

  // DELETE /tokens/:token — revoke a specific token
  hubRouter.delete('/tokens/:token', authMiddleware, async (req, res) => {
    try {
      await tokenManager.update((tokens) => { delete tokens[req.params.token]; });
      res.json({ ok: true });
    } catch {
      res.status(500).json({ error: 'Failed to revoke token' });
    }
  });

  // GET /health — hub process health (public)
  hubRouter.get('/health', (req, res) => {
    res.json({ ok: true, uptime: process.uptime(), gameServerRunning: processManager.running });
  });

  return { villageRouter, hubRouter };
}
